### ISSUE TITLE
okelmann@in.tum.de

### ISSUE THREAD

**Issue by ReimersS** [ReimersS/thesis-bot#4]
Subject:
Thesis applied blockchain for AI driven digital twins in the edge of
 smart cities
Message:
lorem ipsum application number two

Attachments:

**Comment by pogobanane** [comment]
👌

**Comment by pogobanane** [comment]
Hello,

Thank you for your interest in writing a thesis with us. We are pleased to inform you that your application has been accepted, and we look forward to working with you.

As a next step we will set up an interview in order to get to know you better.
The interviewer will send possible dates in a separate eMail.

Kind regards

---------------------------------------------------------------------------
Visit this link to stop these emails: <redacted link>
